server:
    port: "${PORT:8080}"
springdoc:
  version: "${VERSION:1.0.0}"
  swagger-ui:
    path: "/"
spring:
  mvc:
    log-request-details: true
package-zipper:
    maven-url: "https://repo1.maven.org/maven2"
    stream-zipper-url: "${ZIP_STREAMER:bla}"
